package hello_world_soap12_http;

import javax.annotation.Generated;
import javax.jws.*;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2-SNAPSHOT-ba95fa0178063986f7ae2579fda808f1dd7c740e
 * 2019-03-20T09:43:03.117+01:00
 * Generated source version: 3.3.2-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://apache.org/hello_world_doc_lit", name = "Greeter")
@XmlSeeAlso({types.ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.117+01:00", comments = "Apache CXF 3.3.2-SNAPSHOT-ba95fa0178063986f7ae2579fda808f1dd7c740e")
public interface Greeter {

    @WebMethod
    @RequestWrapper(localName = "pingMe", targetNamespace = "http://apache.org/hello_world_doc_lit/types", className = "org.apache.hello_world_doc_lit.types.PingMe")
    @ResponseWrapper(localName = "pingMeResponse", targetNamespace = "http://apache.org/hello_world_doc_lit/types", className = "org.apache.hello_world_doc_lit.types.PingMeResponse")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.117+01:00")
    public void pingMe() throws PingMeFault;

    @WebMethod
    @RequestWrapper(localName = "greetMe", targetNamespace = "http://apache.org/hello_world_doc_lit/types", className = "org.apache.hello_world_doc_lit.types.GreetMe")
    @ResponseWrapper(localName = "greetMeResponse", targetNamespace = "http://apache.org/hello_world_doc_lit/types", className = "org.apache.hello_world_doc_lit.types.GreetMeResponse")
    @WebResult(name = "responseType", targetNamespace = "http://apache.org/hello_world_doc_lit/types")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.117+01:00")
    public String greetMe(
            @WebParam(name = "requestType", targetNamespace = "http://apache.org/hello_world_doc_lit/types")
                    String requestType
    );

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://apache.org/hello_world_doc_lit/types", className = "org.apache.hello_world_doc_lit.types.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://apache.org/hello_world_doc_lit/types", className = "org.apache.hello_world_doc_lit.types.SayHiResponse")
    @WebResult(name = "responseType", targetNamespace = "http://apache.org/hello_world_doc_lit/types")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.117+01:00")
    public String sayHi();

    @WebMethod
    @Oneway
    @RequestWrapper(localName = "greetMeOneWay", targetNamespace = "http://apache.org/hello_world_doc_lit/types", className = "org.apache.hello_world_doc_lit.types.GreetMeOneWay")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.117+01:00")
    public void greetMeOneWay(
            @WebParam(name = "requestType", targetNamespace = "http://apache.org/hello_world_doc_lit/types")
                    String requestType
    );
}
