
package hello_world_soap12_http;

import javax.annotation.Generated;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2-SNAPSHOT-ba95fa0178063986f7ae2579fda808f1dd7c740e
 * 2019-03-20T09:43:03.720+01:00
 * Generated source version: 3.3.2-SNAPSHOT
 */

@WebFault(name = "faultDetail", targetNamespace = "http://apache.org/hello_world_soap12_http/types")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00", comments = "Apache CXF 3.3.2-SNAPSHOT-ba95fa0178063986f7ae2579fda808f1dd7c740e")
public class PingMeFault extends Exception {
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00")
    public static final long serialVersionUID = 1L;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00")
    private types.FaultDetail faultDetail;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00")
    public PingMeFault() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00")
    public PingMeFault(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00")
    public PingMeFault(String message, Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00")
    public PingMeFault(String message, types.FaultDetail faultDetail) {
        super(message);
        this.faultDetail = faultDetail;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00")
    public PingMeFault(String message, types.FaultDetail faultDetail, Throwable cause) {
        super(message, cause);
        this.faultDetail = faultDetail;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-03-20T09:43:03.720+01:00")
    public types.FaultDetail getFaultInfo() {
        return this.faultDetail;
    }
}
